/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package app.vista.textil;

import app.vista.textil.*;
import app.modelo.vo.MateriaPrimaTextilVo;
import app.modelo.vo.MateriaPrimaTextilVo.Unidad;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

/**
 * 
 * @author Hector
 */
public class TextilEditView extends javax.swing.JDialog {

    /**
     * 1- Usar Vo correcto
     */
    private MateriaPrimaTextilVo materiatextil;
    private boolean ok;

    /**
     * 2- Adaptar constructor
     * 2.1 - Usar Vo adecuado en el parametro del constructor
     * @param parent
     * @param modal
     * @param materiatextil
     */
    public TextilEditView(java.awt.Frame parent, boolean modal, MateriaPrimaTextilVo materiatextil) {
        super(parent, modal);
        initComponents();
        this.materiatextil = materiatextil;
        ok = false;
        
        // 2.2 setear los valores de los JComponents adecuadamente
        //init values
        
        txDescripcion.setText(materiatextil.getDescripcion());
        cbUnidad.setSelectedIndex(materiatextil.getUnidad().ordinal());
        txPesoMtrs.setText(String.valueOf(materiatextil.getPesoMtrs()));
        txMtsxPso.setText(String.valueOf(materiatextil.getMtsPso()));
        txMts.setText(String.valueOf(materiatextil.getMts()));
        txPrecio.setText(String.valueOf(materiatextil.getPrecio()));
       
        
        
        bAceptar.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                // 2.4 En este procedimiento, se esta seteando el objeto con los valores
                // del input
                
                getTextil().setDescripcion(txDescripcion.getText());
                getTextil().setUnidad(Unidad.valueOf((String)cbUnidad.getSelectedItem()));
                getTextil().setPesoMtrs(Float.parseFloat(txPesoMtrs.getText()));
                getTextil().setMtsPso(Float.parseFloat(txMtsxPso.getText()));
                getTextil().setMts(Float.parseFloat(txMts.getText()));
                getTextil().setPrecio(Float.valueOf(txPrecio.getText()));
               
                            
                
                
                setOk(true);
                TextilEditView.this.setVisible(false);
            }
        });
        
        bCancelar.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                TextilEditView.this.setVisible(false);
            }
        });

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labels = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        txDescripcion = new javax.swing.JTextField();
        txPrecio = new javax.swing.JTextField();
        bAceptar = new javax.swing.JButton();
        bCancelar = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        txPesoMtrs = new javax.swing.JTextField();
        txMtsxPso = new javax.swing.JTextField();
        txMts = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        cbUnidad = new javax.swing.JComboBox<>();
        buttons = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel8.setText("MtsxPeso");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 160, 110, 31));

        jLabel1.setText("Descripcion");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(42, 32, 81, 31));

        txDescripcion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txDescripcionActionPerformed(evt);
            }
        });
        jPanel1.add(txDescripcion, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 40, 280, -1));
        jPanel1.add(txPrecio, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 260, 280, -1));

        bAceptar.setText("Aceptar");
        jPanel1.add(bAceptar, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 300, 95, 46));

        bCancelar.setText("Cancelar");
        jPanel1.add(bCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 300, 91, 49));

        jLabel9.setText("PesoMtrs");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 110, 140, 31));

        jLabel10.setText("Mts");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 200, 130, 31));

        jLabel12.setText("Precio");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 250, 90, 31));

        txPesoMtrs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txPesoMtrsActionPerformed(evt);
            }
        });
        jPanel1.add(txPesoMtrs, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 120, 280, -1));
        jPanel1.add(txMtsxPso, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 170, 280, -1));
        jPanel1.add(txMts, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 220, 280, -1));

        jLabel11.setText("Unidad");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(42, 75, 140, 31));

        cbUnidad.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "MT", "KG" }));
        jPanel1.add(cbUnidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 80, 280, -1));

        javax.swing.GroupLayout labelsLayout = new javax.swing.GroupLayout(labels);
        labels.setLayout(labelsLayout);
        labelsLayout.setHorizontalGroup(
            labelsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(labelsLayout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 636, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        labelsLayout.setVerticalGroup(
            labelsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(labelsLayout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 387, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout buttonsLayout = new javax.swing.GroupLayout(buttons);
        buttons.setLayout(buttonsLayout);
        buttonsLayout.setHorizontalGroup(
            buttonsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        buttonsLayout.setVerticalGroup(
            buttonsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(buttons, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addComponent(labels, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(labels, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(buttons, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txDescripcionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txDescripcionActionPerformed
        bAceptar.doClick();
    }//GEN-LAST:event_txDescripcionActionPerformed

    private void txPesoMtrsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txPesoMtrsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txPesoMtrsActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bAceptar;
    private javax.swing.JButton bCancelar;
    private javax.swing.JPanel buttons;
    private javax.swing.JComboBox<String> cbUnidad;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel labels;
    private javax.swing.JTextField txDescripcion;
    private javax.swing.JTextField txMts;
    private javax.swing.JTextField txMtsxPso;
    private javax.swing.JTextField txPesoMtrs;
    private javax.swing.JTextField txPrecio;
    // End of variables declaration//GEN-END:variables

    /**
     * 3- Adaptar Vo
     * @return the language
     */
    public MateriaPrimaTextilVo getTextil() {
        return materiatextil;
    }

    /**
     * 4- Adaptar Vo
     * @param materiatextil 
     */
    public void setTextil(MateriaPrimaTextilVo materiatextil) {
        this.materiatextil = materiatextil;
    }

    /**
     * @return the ok
     */
    public boolean isOk() {
        return ok;
    }

    /**
     * @param ok the ok to set
     */
    public void setOk(boolean ok) {
        this.ok = ok;
    }

}
